# Generated by Django 3.2.4 on 2023-06-06 20:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'tests',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='IQTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('timestamp', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_test_result', to='iq_eq_tests.test')),
            ],
            options={
                'verbose_name_plural': 'iq test results',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EQTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_test_result', to='iq_eq_tests.test')),
            ],
            options={
                'verbose_name_plural': 'eq test results',
                'ordering': ['-timestamp'],
            },
        ),
    ]
